# Generated by Django 2.1.5 on 2019-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, "Women's"), (1, "Men's"), (2, 'Unisex'), (3, "Kids'")], default=2),
        ),
    ]
