# Generated by Django 2.1.5 on 2019-02-13 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190211_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Women'), (1, 'Men'), (2, 'Unisex'), (3, "Kids'")], default=2),
        ),
    ]
