# Generated by Django 2.1.5 on 2019-02-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190213_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Women'), (1, 'Men'), (2, 'Unisex'), (3, 'Kids')], default=2),
        ),
    ]
