# Generated by Django 2.1.5 on 2019-02-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_size_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
