# Generated by Django 2.1.5 on 2019-02-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190213_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Women'), (1, 'Men'), (2, 'Unisex'), (3, 'Kids')], default=2),
        ),
    ]
