# Generated by Django 2.1.5 on 2019-02-17 19:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190216_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category'),
        ),
    ]
