# Generated by Django 2.1.5 on 2019-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190225_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
