# Generated by Django 2.1.5 on 2019-02-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
