# Generated by Django 2.1.5 on 2019-02-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190226_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_women',
            new_name='image_gender_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_kids',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_men',
        ),
    ]
