# Generated by Django 2.1.5 on 2019-03-04 08:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20190302_2154'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('my_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
