# Generated by Django 2.1.5 on 2019-03-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20190304_0902'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
