# Generated by Django 2.1.5 on 2019-03-04 09:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20190304_0905'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('comment_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
