# Generated by Django 2.1.5 on 2019-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20190307_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.RemoveField(
            model_name='size',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='size',
            name='label',
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], default=2),
        ),
    ]
