# Generated by Django 2.1.5 on 2019-03-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20190313_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='size',
        ),
    ]
