# Generated by Django 2.1.5 on 2019-03-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20190313_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item_total',
            new_name='cart_total',
        ),
    ]
